### ISSUE TITLE
Does this support parsing map[string]CustomStruct using the `env` tag?

### ISSUE THREAD

**Issue by jasonlimantoro** [ilyakaznacheev/cleanenv#108]
For example, I have the following Config root
```go

var RootConfig Root

type Root struct {
	Http map[string]HttpConfig `yaml:"http" env:"HTTP"`
}

type HttpConfig struct {
	Host      string `yaml:"host"`
	TimeoutMs int    `yaml:"timeout_ms"`
}

func Load(configPath string) {
	cleanenv.ReadConfig(configPath, &RootConfig)
}
```

I know I can provide the following to populate `http` via a `yaml` file:
```yaml
http:
  payment:
    host: "http://payment:4000"
    timeout_ms: 2000
```

But what about the via environment variable? What would `HTTP` look like?
