### ISSUE TITLE
[][]string from env

### ISSUE THREAD

**Issue by mmavka** [ilyakaznacheev/cleanenv#120]
Hello. Thanks for the library. 
I can't figure out how to pass through env [][]string. 
Thank you.

**Comment by 838239178** [comment]
Maybe you should use `map[string]string` and write it as the key-value format.

```yaml
target:
  key1: value1
  key2: value2
```
