### ISSUE TITLE
BUG: env-default overwrites value from yml file

### ISSUE THREAD

**Issue by MichalRybinski** [ilyakaznacheev/cleanenv#40]
Wehnever env-default tag is defined, it's value overwrites value read from yml file (which is not intended behaviour, according to https://github.com/ilyakaznacheev/cleanenv#read-configuration )

100% reproducibility, observed while running go app in vagrant box (ubuntu/bionic).

configs/config.yml
```
# server config
server:
  host: "localhost"
  port: 3000

# database config
db:
  type: "mongodb"
  mongoConfig:
            # full endpoint: address + port
    URL: "mongodb://127.0.0.1:27017"
    ProjectsDBName: "Projects"
    SchemasDBName: "Schemas"
```

config.go
```
package common
package common

import (
  "github.com/ilyakaznacheev/cleanenv"
  "fmt"
)

const YmlConfFile string = "./configs/config.yml"

type AppConfig struct {
	ServerConfig struct {
		PORT string `yaml:"port" env:"MYAPP_PORT" env-default:"3000" env-upd`
		HOST string `yaml:"host" env:"MYAPP_HOST" env-default:"localhost" env-upd`
	} `yaml:"server"`
	DBConfig struct {
		DBType string `yaml:"type" env:"MYAPP_DB_SRV" env-default:"mongodb"`
		MongoConfig struct {
			URL string			`yaml:"URL" env:"MYAPP_DB_URL" env-default:"mongodb://localhost:27017" env-upd`
			ProjectsDB string	`yaml:"ProjectsDBName" env:"MYAPP_PROJECTS_DB" env-default:"TProjects" env-upd`
			SchemasDB string	`yaml:"SchemasDBName"  env:"MYAPP_SCHEMAS_DB" env-default:"TSchemas" env-upd`
		} `yaml:"mongoConfig"`
	} `yaml:"db"`
}

func NewAppConfig(confFilePath string) *AppConfig {
	var AppC AppConfig
    err := cleanenv.ReadConfig(confFilePath, &AppC)
    if err != nil { panic(err) }
	fmt.Println("AppC.DBConfig.MongoConfig.URL %v",AppC.DBConfig.MongoConfig.URL)
	return &AppC
}
```

main.go
```
package main
import "myappp/common"

func main() {
  appConfig := common.NewAppConfig(common.YmlConfFile)
}
```

it prints:
`AppC.DBConfig.MongoConfig.URL %v mongodb://localhost:27017` (as in env-default)

when I remove respective env-default tag with value, e.g.

it prints

`AppC.DBConfig.MongoConfig.URL %v mongodb://127.0.0.1:27017` (as taken from file)

Aside from report above, let me mention that's a great effort to conveniently handle different configuration sources. Thank you!
