### ISSUE TITLE
Problem with bool variable in YAML file

### ISSUE THREAD

**Issue by dikkini** [ilyakaznacheev/cleanenv#61]
yaml file
```yaml
isdebug: false
rule:
  cachesize: 10485760000
```
golang struct
```golang
type AppConfig struct {
	IsDebug bool `env:"RE_IS_DEBUG" env-required:"true"`
	Rule struct {
		CacheSize          int    `env:RULE_CACHE_SIZE" env-required:"true"`
        }
```

i got an error `field \"IsDebug\" is required but the value is not provided"`, but if set `isdebug: true` - all ok, config parse without any errors.
